export const charDet = {
    owner: "asdqwdasd",
    name: "sdawdasd",
    stats: { 
        weapon: 1, 
        accuracy: 1,
        critical: 1, 
        dex: 1, 
        strength: 1, 
        magic: 1, 
        spd: 3.4,
        atkSpd: .9,
    },
    lvl: 1,
    rank: "none",
    hp: 300,
    maxHp: 300,
    mp: 100,
    maxMp: 100,
    sp: 100,
    maxSp: 100,
    exp: 0,
    maxExp: 100,
    x: 0,
    z: 0,
    cloth: "rudeus",
    pants: "brown",
    hair: "aegon",
    boots: "silverboots",
    skinColor: {r: 0, g: 0, b: 0, name: ""},
    hairColor: {r: 0, g: 0, b: 0},
    clothColor: {r: 0, g: 0, b: 0},
    pantsColor: {r: 0, g: 0, b: 0},
    items: [],
    skills: [
        {
            name: "flexaura",
            lvl: 1,
            pointsToClaim: 1,
            pointsForUpgrade: 1,
            element: "normal",
            requireMode: "any",
            skillType: "na",
            animationLoop: false,
            displayName: "Flex aura",
            castDuration: 10,
            returnModeDura: 900,
            skillCoolDown: 2000,
            demand: [
                {
                    name: "mp",
                    minCost: 1,
                    cost: 0.3
                }
            ],
            effects: {
                effectType: "buff",
                dmgPm: 0,
                plusDmg: 0,
                chance: 0,
                bashPower: 0,
            },
            skillrank: 6,
            upgradePlus: 60,
            desc: "You can conceal and show your aura, This is best to do when you want someone to easily spot you in some certain places. Your aura can be dense depends on your magic force."
        }
    ],
    titles: [],

    currentPlace: {
        placeId: "room101",
        name: "room",
        areaType: "room",
    },
    places: [],
    status: [],
    regens: {sp: 0, hp: 0, mana: 0},
    monsSoul: 1,
    coins: 0,
    assets: { 
        krit: 0,
        fins: 0,
        dramite: 0,
    },
    survival: { hunger: 100, sleep: 100 },
    aptitude: [],
    monsterKilled: 0,
    defeatedMonsters: [],
    blessings: [],
    stories: [],
    quests: [],
    clearedQuests: [],
    race: "human",
    characterType: "player",
    lastSpoken: "none",
    deadCount: 1,
    isDead: false
}